default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *default
  database: demo_deploy_development

test:
  <<: *default
  database: demo_deploy_test

production:
  <<: *default
  database: demo_deploy_production
  username: demo_deploy
  password: 1
